#!/bin/bash
# assemble-config.sh — Merge platform.yml + active project config → product.yml
# Called on boot (entrypoint.sh) and on project switch (switch-project.sh).
# All existing scripts continue reading config/product.yml unchanged.

CABINET_ROOT="${CABINET_ROOT:-/opt/founders-cabinet}"
PLATFORM_FILE="$CABINET_ROOT/config/platform.yml"
PROJECTS_DIR="$CABINET_ROOT/config/projects"
OUTPUT_FILE="$CABINET_ROOT/config/product.yml"
ACTIVE_FILE="$CABINET_ROOT/config/active-project.txt"

# Determine active project from Redis → file fallback
if command -v redis-cli &>/dev/null; then
  REDIS_HOST="${REDIS_HOST:-redis}"
  REDIS_PORT="${REDIS_PORT:-6379}"
  SLUG=$(redis-cli -h "$REDIS_HOST" -p "$REDIS_PORT" GET "cabinet:active-project" 2>/dev/null)
fi

# Fallback to file if Redis is empty or unavailable
if [ -z "$SLUG" ] || [ "$SLUG" = "(nil)" ]; then
  if [ -f "$ACTIVE_FILE" ]; then
    SLUG=$(cat "$ACTIVE_FILE" | tr -d '[:space:]')
  fi
fi

if [ -z "$SLUG" ]; then
  echo "[assemble-config] ERROR: No active project. Set cabinet:active-project in Redis or config/active-project.txt" >&2
  exit 1
fi

PROJECT_FILE="$PROJECTS_DIR/${SLUG}.yml"
if [ ! -f "$PROJECT_FILE" ]; then
  echo "[assemble-config] ERROR: Project config not found: $PROJECT_FILE" >&2
  exit 1
fi

if [ ! -f "$PLATFORM_FILE" ]; then
  echo "[assemble-config] ERROR: Platform config not found: $PLATFORM_FILE" >&2
  exit 1
fi

# Merge: platform.yml has shared keys, project file has project-specific keys.
# They have non-overlapping top-level keys, so cat works cleanly.
# captain_name from platform.yml goes under product: in the output for backward compat.
{
  echo "# =============================================================  "
  echo "# Founder's Cabinet — Product Configuration (AUTO-GENERATED)"
  echo "# =============================================================  "
  echo "# This file is generated by assemble-config.sh from:"
  echo "#   config/platform.yml + config/projects/${SLUG}.yml"
  echo "# Do not edit directly — edit the source files instead."
  echo "# Active project: ${SLUG}"
  echo "# Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
  echo "# =============================================================  "
  echo ""
  cat "$PROJECT_FILE"
  echo ""
  # Extract captain_name from platform and inject into product section
  # (send-voice.sh reads captain_name under product:)
  CAPTAIN_NAME=$(grep '^captain_name:' "$PLATFORM_FILE" | awk '{print $2}' | tr -d '"' | tr -d "'")
  if [ -n "$CAPTAIN_NAME" ]; then
    # Append captain_name to the product section (after mount_path line)
    # But since product.yml is flat, just add it to the product: block via sed later
    true
  fi
  echo ""
  # Append platform config (skip the captain_name line since it goes under product:)
  grep -v '^captain_name:' "$PLATFORM_FILE" | grep -v '^#.*Platform Configuration' | grep -v '^# Settings that stay' | grep -v '^# Officer personalities' | grep -v '^# This file is merged'
} > "$OUTPUT_FILE.tmp"

# Inject captain_name into product: section if present
if [ -n "$CAPTAIN_NAME" ]; then
  sed -i "/^  mount_path:/a\\  captain_name: ${CAPTAIN_NAME}" "$OUTPUT_FILE.tmp" 2>/dev/null || true
fi

mv "$OUTPUT_FILE.tmp" "$OUTPUT_FILE"
echo "[assemble-config] Assembled: platform.yml + projects/${SLUG}.yml → product.yml"
